# Generated by Django 5.0.4 on 2026-04-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_guardian_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('cash', 'Cash'), ('stripe', 'Stripe (Card)'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=20),
        ),
    ]
