/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#2b5ab5',
        'primary-container': '#4874cf',
        'primary-fixed': '#d9e2ff',
        'primary-fixed-dim': '#b0c6ff',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#001945',
        'on-primary-fixed-variant': '#00429c',
        'on-primary-container': '#ffffff',
        secondary: '#4c616c',
        'secondary-container': '#cfe6f2',
        'secondary-fixed': '#cfe6f2',
        'secondary-fixed-dim': '#b4cad6',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#071e27',
        'on-secondary-fixed-variant': '#354a53',
        'on-secondary-container': '#526772',
        tertiary: '#1a6c23',
        'tertiary-container': '#37863a',
        'tertiary-fixed': '#a3f69c',
        'tertiary-fixed-dim': '#88d982',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#002204',
        'on-tertiary-fixed-variant': '#005312',
        'on-tertiary-container': '#ffffff',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        surface: '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-variant': '#e1e3e4',
        'surface-tint': '#2b5bb5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'on-surface': '#191c1d',
        'on-surface-variant': '#414754',
        background: '#f8f9fa',
        'on-background': '#191c1d',
        outline: '#727785',
        'outline-variant': '#c1c6d6',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        'inverse-primary': '#b0c6ff',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
