# Generated by Django 5.0.4 on 2026-04-07 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UDISEProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udise_code', models.CharField(max_length=11, unique=True)),
                ('block_code', models.CharField(blank=True, max_length=10)),
                ('district_code', models.CharField(blank=True, max_length=10)),
                ('state_code', models.CharField(blank=True, max_length=10)),
                ('school_category', models.CharField(choices=[('primary', 'Primary'), ('upper_primary', 'Upper Primary'), ('secondary', 'Secondary'), ('higher_secondary', 'Higher Secondary'), ('composite', 'Composite')], default='composite', max_length=20)),
                ('school_type', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('co_ed', 'Co-educational')], default='co_ed', max_length=10)),
                ('management_type', models.CharField(choices=[('govt', 'Government'), ('private_aided', 'Private Aided'), ('private_unaided', 'Private Unaided'), ('central_govt', 'Central Government')], default='private_unaided', max_length=20)),
                ('medium', models.CharField(max_length=60)),
                ('year_established', models.IntegerField()),
                ('affiliation_board', models.CharField(max_length=60)),
                ('affiliation_number', models.CharField(blank=True, max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'U-DISE Profile',
                'verbose_name_plural': 'U-DISE Profile',
                'db_table': 'udise_profile',
            },
        ),
        migrations.CreateModel(
            name='UDISEAnnualData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_data', models.JSONField(default=dict)),
                ('teacher_data', models.JSONField(default=dict)),
                ('infrastructure', models.JSONField(default=dict)),
                ('cwsn_count', models.IntegerField(default=0)),
                ('rte_count', models.IntegerField(default=0)),
                ('minority_count', models.IntegerField(default=0)),
                ('mid_day_meal', models.BooleanField(default=False)),
                ('has_boundary_wall', models.BooleanField(default=False)),
                ('has_ramp', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('exported', 'Exported')], default='draft', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='udise_data', to='shared.academicyear')),
            ],
            options={
                'verbose_name': 'U-DISE Annual Data',
                'verbose_name_plural': 'U-DISE Annual Data',
                'db_table': 'udise_annual_data',
                'ordering': ['-academic_year__start_date'],
            },
        ),
        migrations.CreateModel(
            name='UDISEExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel')], max_length=10)),
                ('record_count', models.IntegerField(default=0)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='udise_exports', to='shared.academicyear')),
                ('exported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='udise_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'U-DISE Export Log',
                'db_table': 'udise_export_logs',
                'ordering': ['-exported_at'],
            },
        ),
    ]
