# Generated by Django 5.0.4 on 2026-04-03 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('principal', 'Principal'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=20),
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('forgot_password', 'Forgot Password')], max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'otps',
                'indexes': [models.Index(fields=['email', 'purpose', 'is_used'], name='otps_email_32bf71_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserTourProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_key', models.CharField(max_length=60)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_tour_progress',
                'indexes': [models.Index(fields=['user', 'tour_key'], name='user_tour_p_user_id_c623a7_idx')],
                'unique_together': {('user', 'tour_key')},
            },
        ),
    ]
