# Generated by Django 5.0.4 on 2026-04-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role_otp_usertourprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('principal', 'Principal'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=20),
        ),
    ]
