# Generated by Django 5.0.4 on 2026-04-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('finance', 'Finance'), ('principal', 'Principal'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=20),
        ),
    ]
