# Generated by Django 5.0.4 on 2026-04-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('principal', 'Principal'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=20, unique=True)),
                ('prefix', models.CharField(help_text='3 uppercase letters, e.g. MAJ', max_length=3)),
                ('year', models.CharField(help_text='4-digit year, e.g. 1998', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'id_configurations',
            },
        ),
    ]
