# Generated by Django 5.0.4 on 2026-04-06 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_idconfiguration'),
        ('shared', '0001_initial'),
        ('student', '0003_alter_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_templates', to='shared.academicyear')),
                ('grade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_template', to='shared.grade')),
            ],
            options={
                'db_table': 'fee_templates',
                'unique_together': {('grade', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='FeeTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_optional', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='admin_panel.feetemplate')),
            ],
            options={
                'db_table': 'fee_template_items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('scholarship', 'Scholarship'), ('sibling', 'Sibling Discount'), ('merit', 'Merit Award'), ('financial_aid', 'Financial Aid'), ('staff_child', 'Staff Child'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='student.studentprofile')),
            ],
            options={
                'db_table': 'student_discounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
