# Generated by Django 5.0.4 on 2026-04-07 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        ('student', '0003_alter_payment_method'),
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cert_type', models.CharField(choices=[('tc', 'Transfer Certificate'), ('bonafide', 'Bonafide Certificate'), ('character', 'Character Certificate'), ('migration', 'Migration Certificate'), ('conduct', 'Conduct Certificate'), ('study', 'Study Certificate')], max_length=20)),
                ('body_template', models.TextField(help_text='Use {{placeholders}} like {{student_name}}, {{father_name}}, {{class}}, {{date_of_birth}}')),
                ('header_image', models.ImageField(blank=True, upload_to='certificates/headers/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'certificate_templates',
            },
        ),
        migrations.CreateModel(
            name='IssuedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=30, unique=True)),
                ('issued_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('date_of_admission', models.DateField(blank=True, null=True)),
                ('date_of_leaving', models.DateField(blank=True, null=True)),
                ('class_at_leaving', models.CharField(blank=True, max_length=30)),
                ('reason_for_leaving', models.CharField(blank=True, max_length=100)),
                ('conduct', models.CharField(blank=True, max_length=100)),
                ('qualified_for_promotion', models.BooleanField(null=True)),
                ('working_days', models.IntegerField(blank=True, null=True)),
                ('days_present', models.IntegerField(blank=True, null=True)),
                ('rendered_body', models.TextField(blank=True, help_text='Final rendered certificate text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='student.studentprofile')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.certificatetemplate')),
            ],
            options={
                'db_table': 'issued_certificates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('board_type', models.CharField(choices=[('cbse', 'CBSE'), ('icse', 'ICSE'), ('state_board', 'State Board'), ('custom', 'Custom')], default='cbse', max_length=20)),
                ('grading_scale', models.CharField(choices=[('marks', 'Marks Only'), ('grades', 'Grades Only'), ('both', 'Marks + Grades')], default='both', max_length=10)),
                ('co_scholastic_areas', models.JSONField(blank=True, default=list, help_text='e.g. [{"area": "Work Education", "grade": "A"}, ...]')),
                ('show_attendance', models.BooleanField(default=True)),
                ('show_remarks', models.BooleanField(default=True)),
                ('show_rank', models.BooleanField(default=False)),
                ('header_text', models.TextField(blank=True)),
                ('footer_text', models.TextField(blank=True)),
                ('principal_signature', models.ImageField(blank=True, upload_to='report_cards/signatures/')),
                ('school_seal', models.ImageField(blank=True, upload_to='report_cards/seals/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='shared.academicyear')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='shared.grade')),
            ],
            options={
                'db_table': 'report_card_templates',
                'unique_together': {('grade', 'academic_year', 'board_type')},
            },
        ),
        migrations.CreateModel(
            name='ReportCardTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('term1', 'Term 1 / Half Yearly'), ('term2', 'Term 2 / Annual'), ('midterm', 'Mid-Term'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20)),
                ('grade_thresholds', models.JSONField(blank=True, default=list, help_text='e.g. [{"min": 91, "max": 100, "grade": "A1"}, {"min": 81, "max": 90, "grade": "A2"}, ...]')),
                ('assessments', models.ManyToManyField(blank=True, related_name='report_terms', to='teacher.assessment')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.reportcardtemplate')),
            ],
            options={
                'db_table': 'report_card_terms',
                'unique_together': {('template', 'term')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_snapshot', models.JSONField(default=dict, help_text='Full report card data frozen at generation time')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('distributed', 'Distributed')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.academicyear')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='student.studentprofile')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.reportcardtemplate')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.reportcardterm')),
            ],
            options={
                'db_table': 'generated_report_cards',
                'ordering': ['-generated_at'],
                'unique_together': {('student', 'template', 'term')},
            },
        ),
    ]
