# Generated by Django 5.0.4 on 2026-04-07 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('annual_quota', models.IntegerField(default=12)),
                ('carries_forward', models.BooleanField(default=False)),
                ('applicable_to', models.CharField(choices=[('staff', 'Staff'), ('student', 'Student'), ('both', 'Both')], default='staff', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'leave_types',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='leave_types_code_8c30f5_idx'), models.Index(fields=['applicable_to', 'is_active'], name='leave_types_applica_70db83_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_half_day', models.BooleanField(default=False)),
                ('reason', models.TextField()),
                ('attachment', models.FileField(blank=True, upload_to='leave_attachments/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='leave.leavetype')),
            ],
            options={
                'db_table': 'leave_applications',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='leave.leaveapplication')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_approvals_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_approvals',
                'indexes': [models.Index(fields=['approver', 'acted_at'], name='leave_appro_approve_1631b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated', models.IntegerField(default=0)),
                ('used', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('carried_forward', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='shared.academicyear')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='leave.leavetype')),
            ],
            options={
                'db_table': 'leave_balances',
                'indexes': [models.Index(fields=['user', 'academic_year'], name='leave_balan_user_id_da28cd_idx')],
                'unique_together': {('user', 'leave_type', 'academic_year')},
            },
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['applicant', 'status'], name='leave_appli_applica_dcbc4c_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['status', 'applied_at'], name='leave_appli_status_980627_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['start_date', 'end_date'], name='leave_appli_start_d_424510_idx'),
        ),
    ]
